# Site settings
name: Thales Posella
description: "Session Musician | Mixing Engineer"
url: "www.thalesposella.com"
title: "Thales Posella | Session Musician & Mixing Engineer"

# Delete the lines you don't need
# about 5 elements are recomended
github_username: platanus-xx
facebook_username: platanusmaple
twitter_username: thales_posella
youtube_username: thalesposella
instagram_username: thalesposella
email: contact@thalesposella.com
# email: thales.studio@gmail.com

avatar: yes
avatar_img_path: "imgs/avatar.jpg"

mavens: yes
mavens_path: "imgs/mavens.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty
