# Site settings
name: Thales Posella
description: "Session Musician | Mixing Engineer"
url: "www.thalesposella.com"
title: "Thales Posella | Session Musician & Mixing Engineer"

# about 5 elements are recomended
github_username: platanus-xx
facebook_username: platanusmaple
x_username: thales_posella
youtube_username: thalesposella
instagram_username: thalesposella
email: contact@thalesposella.com

avatar: yes
avatar_img_path: "imgs/avatar.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.png"

# Build settings
markdown: kramdown
permalink: pretty

# Jekyll server folder
destination: ./_public
livereload: true

# the mavens telescope
mavens_background_img: yes
mavens_logo: "../imgs/mavens_logo.png"
mavens_background_path: "../imgs/mavens_background.png"
mavens_name: The Mavens Telescope
mavens_description: "Independent Rock Band"
mavens_endurance_img: yes
mavens_endurance_path: "../imgs/mavens_endurance.png"
mavens_seeds_img: yes
mavens_seeds_path: "../imgs/mavens_seeds.jpg"
mavens_favicon: "../imgs/mavens_favicon.png"
mavens_yt_username: MavensTelescope
mavens_insta_username: mavenstelescope